cache:
  container_name: ieeeutd_cache
  image: redis
api:
  container_name: ieeeutd_api
  build: ./images/api/
  volumes:
    - .:/ieeeutd-api/
    - .:/ieeeutd-api/.git/
  working_dir: /ieeeutd-api/
  command: npm run dev
  environment:
    - SESSION_SECRET=aASKF4AFjas52wFSAF
    - CACHE_HOST=cache
    - MAIL_HOSTNAME=http://dev.ieeeutd.org
  ports:
    - "8000:3000"
  links:
    - database
    - cache
nginx:
  container_name: ieeeutd_nginx
  image: nginx
  volumes:
    - ./images/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
  ports:
    - "80:80"
  links:
    - api
database:
  container_name: ieeeutd_db
  image: mongo:4.0
  ports:
    - "27000:27017"
